title: Linux Hacks
email: your-email@example.com
description: ""

domain: asiangoldfish.github.io
url: https://asiangoldfish.github.io/LinuxHacks
baseurl: ""
github_username: asiangoldfish

theme: just-the-docs
remote_theme: pages-themes/minimal@v0.2.0

plugins:
- jekyll-remote-theme

color_scheme: dark

# Define collections
collections:
  docs:
    permalink: ":path:output_ext"
    output: true

just_the_docs:
  collections:
    docs:
      name: Documentation
      nav_exclude: false
      search_exclude: false

aux_links:
  "Just the Docs on GitHub":
    - "//github.com/just-the-docs/just-the-docs"