title: Linux Hacks
email: your-email@example.com
description: ""

domain: asiangoldfish.github.io
url: https://asiangoldfish.github.io/LinuxHacks
baseurl: "docs"
github_username: asiangoldfish

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

color_scheme: dark

# Define collections
collections:
  docs:
    permalink: ":path:output_ext"
    output: true

just_the_docs:
  collections:
    docs:
      name: Documentation
      nav_exclude: false
      search_exclude: false

aux_links:
  "Just the Docs on GitHub":
    - "//github.com/just-the-docs/just-the-docs"