source "https://rubygems.org"
gem "jekyll"
gem "just-the-docs"
gem "webrick"

group :jekyll_plugins do
  gem "github-pages", "~>	226"
  gem "jekyll-feed", "~> 0.12"
  gem 'jekyll-remote-theme'
end

gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
