title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "docs" # uncomment this for development server

url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  asiangoldfish

theme: just-the-docs
remote-theme: just-the-docs

color_scheme: dark

# Define collections
collections:
  docs:
    permalink: ":path:output_ext"
    output: true

just_the_docs:
  collections:
    docs:
      name: Documentation
      nav_exclude: false
      search_exclude: false

aux_links:
  "Just the Docs on GitHub":
    - "//github.com/just-the-docs/just-the-docs"